### ISSUE TITLE
Transcoding fullHD videos does not work on Android

### ISSUE THREAD

**Issue by OnlineEngineer** [jbavari/cordova-plugin-video-editor#103]
First of all, I'd like to thank for the plug-in - great work!!

Unfortunately, it seems that transcoding fullHD videos (1920x1080) leads to an error on Android. The error code is undefined. It happens every time on all Android devices I have tested with. Videos with a lower resolution can be transcoded without any problems. Is this a known issue?

Many thanks in advance.

PS: tested with v1.1.2

**Comment by Redmage3555** [comment]
I think I've encountered this same issue. When trying to transcode a 1920x1080 video to a lower videoBitrate (but same dimensions), I get a java.lang.IllegalStateException. Here's the Android Studio output:

```
E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
E/ACodec:  configureCodec multi window instance fail  appPid : 24759
E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -38
E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -38)
E/MediaTranscoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
                   java.lang.IllegalStateException
                       at android.media.MediaCodec.native_configure(Native Method)
                       at android.media.MediaCodec.configure(MediaCodec.java:262)
                       at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.setup(VideoTrackTranscoder.java:91)
                       at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.setupTrackTranscoders(MediaTranscoderEngine.java:179)
                       at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:98)
                       at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:179)
                       at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:160)
                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                       at java.lang.Thread.run(Thread.java:841)
D/VideoEditor: transcode exception
               java.lang.IllegalStateException
                   at android.media.MediaCodec.native_configure(Native Method)
                   at android.media.MediaCodec.configure(MediaCodec.java:262)
                   at net.ypresto.androidtranscoder.engine.VideoTrackTranscoder.setup(VideoTrackTranscoder.java:91)
                   at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.setupTrackTranscoders(MediaTranscoderEngine.java:179)
                   at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:98)
                   at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:179)
                   at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:160)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                   at java.lang.Thread.run(Thread.java:841)
D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 253 : Transcoding failed: java.lang.IllegalStateException
I/chromium: [INFO:CONSOLE(253)] "Transcoding failed: java.lang.IllegalStateException", source: file:///android_asset/www/js/index.js (253)
E/qdmemalloc: heap_msk=3000000 flags=1
```

Any thoughts on what may be causing this?
