### ISSUE TITLE
Plugin won't compile with Cordova 5

### ISSUE THREAD

**Issue by karvapallo** [jbavari/cordova-plugin-video-editor#26]
I'm not able to build my project after upgrading to Cordova 5. This plugin was the culprit.

Here's the relevant build error:

```
:processDebugManifest/Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/AndroidManifest.xml:7:53 Error:
	Attribute application@icon value=(@drawable/icon) from AndroidManifest.xml:7:53
	is also present at android.org.apache.cordova.videoeditor:android-ffmpeg-java:unspecified:debug:12:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:7:5 to override
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/icon) from AndroidManifest.xml:7:53
  	is also present at android.org.apache.cordova.videoeditor:android-ffmpeg-java:unspecified:debug:12:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:7:5 to override

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.015 secs

/Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/username/Projects/torreville-update/frontend/TorreVille/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by rossmartin** [comment]
Have you tried this workaround mentioned in #24 ?

"Workaround:

Add `xmlns:tools="http://schemas.android.com/tools"` to your manifest tag in AndroidManifest.xml and `tools:replace="android:icon"` in your application tag.

This works for me."

I'm going to be updating an app of mine soon and will look into this.

Thanks.

**Comment by rossmartin** [comment]
fixed via https://github.com/jbavari/cordova-plugin-video-editor/commit/ab2bc260886eb75eb82238f1b4b96e0f63e9091f
