### ISSUE TITLE
videoTranscodeError, err: android.media.MediaCodec$CodecException: Error 0xfffffc03

### ISSUE THREAD

**Issue by ayyazzafar** [jbavari/cordova-plugin-video-editor#95]
I am getting following error during transcoding a video recorded by front camera

videoTranscodeError, err: android.media.MediaCodec$CodecException: Error 0xfffffc03

Is there any solution for this?

**Comment by lsilvs** [comment]
Check it out: https://github.com/jbavari/cordova-plugin-video-editor/issues/90

Maybe it can help you.

Cheers,

**Comment by ayyazzafar** [comment]
Thanks a lot. I'll review it, check and will let you know.

Also kindly try to help with this issue https://github.com/jbavari/cordova-plugin-video-editor/issues/91

I'll really appreciate.

Thanks in Advance.

**Comment by PriceFallin** [comment]
I have v1.1.2 with these changes include from #90 but for some reason I'm still getting the error when I either change the height/width to a larger number (ex. 720) or just exclude the width and height from the options.

The weirdest part is that it does work out when I include the sizing 640 just like it's shown in the documentation. I've tried trouble shooting for a bit but no luck yet.

**Comment by damiantw** [comment]
Same, receive this error on 1.1.2 when I do not set a height/width. Works fine on 1.1.1.

**Comment by factionfour** [comment]
On version 1.1.2, when using a number like 720 for height I am also receiving this error.  When using a height of 640 it is successful.

**Comment by danielflippance** [comment]
Thanks @PriceFallin You saved my night!

**Comment by rahulbaboria** [comment]
[OMX.qcom.video.encoder.avc] configureCodec returning error -1010
12-01 10:57:12.104 9379-9473/com.urcaddy E/ACodec: signalError(omxError 0x80001001, internalError -1010)
12-01 10:57:12.104 9379-9472/com.urcaddy E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
12-01 10:57:12.104 9379-9471/com.urcaddy E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
12-01 10:57:12.116 9379-9471/com.urcaddy E/AndroidRuntime: FATAL EXCEPTION: TextureMovieEncoder
                                                           Process: com.urcaddy, PID: 9379
                                                           android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                               at android.media.MediaCodec.native_configure(Native Method)
                                                               at android.media.MediaCodec.configure(MediaCodec.java:1935)
                                                               at android.media.MediaCodec.configure(MediaCodec.java:1864)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.VideoEncoderCore.<init>(VideoEncoderCore.java:79)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:381)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:312)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.TextureMovieEncoder.access$100(TextureMovieEncoder.java:61)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:281)
                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at com.urcaddy.controller.activities.myswings.videocapture.TextureMovieEncoder.run(TextureMovieEncoder.java:248)
                                                               at java.lang.Thread.run(Thread.java:764)

I'm getting this in oreo devices , can i get some idea how to solve this?
